name: Install Export Templates
description: Installs export templates for the Godot Engine to the path for the duration of the current job.
inputs:
  version:
    description: "Version, e.g. 4.6-stable"
    required: true
  sha_256:
    description: "SHA-256 checksum of the zip file from the release page"
    required: true
runs:
  using: "composite"
  steps:
    - shell: "bash"
      env:
        TEMPLATES_ZIP: "Godot_v${{ inputs.version }}_export_templates.tpz" # Does not work with mono builds as they have a separate template archive
      run: |
        curl -LO "https://github.com/godotengine/godot/releases/download/${{ inputs.version }}/${{ env.TEMPLATES_ZIP }}"
        echo "${{ inputs.sha_256 }} ${{ env.TEMPLATES_ZIP }}" | sha256sum -c
        unzip ${{ env.TEMPLATES_ZIP }} # .tpz is just a renamed zip, see https://docs.godotengine.org/en/stable/tutorials/export/exporting_projects.html#export-templates
        rm ${{ env.TEMPLATES_ZIP }}
        VERSION=${{ inputs.version }} # So it can be used in shell parameter expansion
        VERSION_DIR=${VERSION/%-stable/.stable} # TODO: unsure what the transformation is for non-stable releases
        TEMPLATES_DIR="$HOME/.local/share/godot/export_templates/$VERSION_DIR"
        mkdir -p $TEMPLATES_DIR
        mv ./templates/* $TEMPLATES_DIR
        rm -rf ./templates

