name: Install Godot Engine
description: Installs the Godot Engine to the path for the duration of the current job, invokable with the command "godot"
inputs:
  version:
    description: "Version, e.g. 4.6-stable"
    required: true
  sha_256:
    description: "SHA-256 checksum of the zip file from the release page. If provided, then the action will fail on a checksum mismatch."
    required: false
    default: ""
  platform:
    description: "Platform as it appears in the binary name, e.g. linux.x86_64"
    default: "linux.x86_64"
runs:
  using: "composite"
  steps:
    - name: Restore Cached Godot
      id: cache-godot-restore
      uses: actions/cache/restore@v6
      with:
        path: Godot_v${{ inputs.version }}_${{ inputs.platform }}
        key: ${{ runner.os }}-${{ inputs.version }}-${{inputs.platform}}-godot
    - name: Get Godot
      if: steps.cache-godot-restore.outputs.cache-hit != 'true'
      shell: "bash"
      env:
        GODOT_ZIP: "Godot_v${{ inputs.version }}_${{ inputs.platform }}.zip" # Does not work with mono builds as they use an underscore instead of a dot in the zip filenames
      run: |
        curl -LO "https://github.com/godotengine/godot/releases/download/${{ inputs.version }}/${{ env.GODOT_ZIP }}"
        if [[ -n "${{ inputs.sha_256 }}" ]] && ! (echo "${{ inputs.sha_256 }} ${{ env.GODOT_ZIP }}" | sha256sum -c); then
            exit 1
        fi
        unzip ${{ env.GODOT_ZIP }}
        rm ${{ env.GODOT_ZIP }}
    - name: Save Godot to Cache
      id: cache-godot-save
      uses: actions/cache/save@v6
      with:
        path: Godot_v${{ inputs.version }}_${{ inputs.platform }}
        key: ${{ steps.cache-godot-restore.outputs.cache-primary-key }}
    - name: Move Godot and Add to PATH
      shell: "bash"
      env:
        GODOT_FILE: "Godot_v${{ inputs.version }}_${{ inputs.platform }}"
      run: |
        BIN_DIR=${{ runner.temp }}/godot-bin
        mkdir -p $BIN_DIR
        mv ${{ env.GODOT_FILE }} $BIN_DIR/godot
        echo "$BIN_DIR" >> "$GITHUB_PATH" # Documented at https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#adding-a-system-path
