name: Build, Test and Publish
on:
  push:
    branches:
      - "*"
  release:
    types: [published]

env:
  GODOT_VERSION: "4.6-stable"

permissions:
  contents: write

jobs:
  build:
    name: Build All
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Install Godot Engine
        uses: "./.github/actions/install-godot"
        with:
          version: "4.6-stable"
          sha_256: "6bcc59dfd1d670e918c77eae06e82b9dc5699de13d353dc3a4b3b6b307b6dc06"
          platform: "linux.x86_64"
      - name: Install Export Templates
        uses: "./.github/actions/install-export-templates"
        with:
          version: "4.6-stable"
          sha_256: "3b30ac8c1772f25f5dfa5f65922cab0a90e7b960176891237c5772515ebccc46"
      - name: Build Example Game
        run: make
      - name: Package Game
        run: |
          mkdir zip_root
          mv build/linux/* zip_root
          cd zip_root && tar -czf \
            "../sv-mod-loader-example-game-linux.x86_64-${{ github.ref_name }}.tar.gz" \
            ./*
      - name: Upload Example Game Artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-game
          path: sv-mod-loader-example-game-*.*
      - name: Build Example Mods
        run: make example-mods
      - name: Package Example Mods
        run: |
          mkdir zip_root
          mv example-mods/*/build/*.pck zip_root
          (cd zip_root && zip -r \
            "../sv-mod-loader-example-mods-${{ github.ref_name }}.zip" \
            ./*)
          (cd zip_root && tar -czf \
            "../sv-mod-loader-example-mods-${{ github.ref_name }}.tar.gz" \
            ./*)
      - name: Upload Example Mods Artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-mods
          path: sv-mod-loader-example-mods-*.*
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Run gdUnit4 Tests
        uses: MikeSchulze/gdUnit4-action@v1
        with:
          godot-version: "4.6"
          godot-status: "stable"
          paths: |
            res://test
          version: "v6.1.1"
          publish-report: false # true causes failure due to read-only permission
  archive-addon:
    name: Package Addon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Archive Addon
        run: |
          mkdir zip_root
          mkdir zip_root/addons
          cp -r addons/sv_mod_loader zip_root/addons
          (cd zip_root && zip -r \
            "../sv-mod-loader-addon-${{ github.ref_name }}.zip" \
            ./*)
          (cd zip_root && tar -czf \
            "../sv-mod-loader-addon-${{ github.ref_name }}.tar.gz" \
            ./*)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: addon-archives
          path: |
            sv-mod-loader-addon-${{ github.ref_name }}.zip
            sv-mod-loader-addon-${{ github.ref_name }}.tar.gz
  publish:
    name: Publish release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download packaged addons
        uses: actions/download-artifact@v8
        with:
          name: addon-archives
          skip-decompress: false
          merge-multiple: false
      - name: Download example game (all platforms)
        uses: actions/download-artifact@v8
        with:
          name: example-game
          skip-decompress: false
          merge-multiple: true
      - name: Download example mods
        uses: actions/download-artifact@v8
        with:
          name: example-mods
          skip-decompress: false
          merge-multiple: true
      - name: Release artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload \
            "${{ github.ref_name }}" \
            sv-mod-loader-addon-*.* \
            sv-mod-loader-example-game-*.* \
            sv-mod-loader-example-mods-*.* \
            --repo "${{ github.repository }}"
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Copy patch notes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release edit \
            "${{ github.ref_name }}" \
            --repo "${{ github.repository }}" \
            --notes-file release-notes/$(if [ -f release-notes/${{ github.ref_name }}.md ]; then echo "${{ github.ref_name }}.md"; else echo "latest.md"; fi)

